apiVersion: batch/v1
kind: Job
metadata:
  name: solrguard-run
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: solrguard
          image: solrguard:local
          command: ["solrguard"]
          args:
            - "run"
            - "examples/changesets/fieldtype-change.yaml"
            - "--out"
            - "out/k8s_run"
